name: mhu_dart_annotation
version: 1.0.1
description: Common annotations used in my Dart and Flutter projects
repository: https://github.com/maprohu/mhu_dart_annotation

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
